### PR TITLE
change to make punch remove the plant first

### LINKED ISSUE #17: detaching a flowerpot with a flower in it loses the pot
when the node below an empty flower pot is broken, the pot drops as an item.

when the node below a pot with a flower is broken, the flower drops as an item, and the pot disappears.

this is because digging the pot is expected to just drop the flower, and the pot will be re-added in the `after_dig_node` callback. however, the code governing attached nodes isn't aware of that callback. i'm not sure it should be, either. 

if anyone who has a good suggestion about to handle this, i'd be happy to hear it.

### PR DESCRIPTION
**Pull request by yl-whosit**
One of the ways to fix https://github.com/minetest-mods/flowerpot/issues/17

### CODE REVIEW

**Comment by SmallJoker** [comment]
This needs protection checks. Otherwise players could steal flowers on multiplayer worlds / servers.

**Comment by yl-whosit** [comment]
Sorry, totally forgot :)
(and fixed now)

**Comment by SmallJoker** [comment]
I would have preferred digging the flower pot twice: once to remove the flower and once to remove the pot. Whereas latter is possible, the former does not seem to have a way to differentiate between dropping of `attached_node` or digging it.

Looks good. Will merge in a few days unless there are objections.

**Comment by yl-whosit** [comment]
Yes, this is just one possible hacky workaround...

Other way could be to check in `after_dig_node` if there's a node below that pot can stand on?

I'm not sure how to do that exactly though or if it would work.

**Pull request merged**
